name: Deploy a Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar (build)
        run: npm run build
        env:
          VITE_FIREBASE_PHOTOS_API_KEY: ${{ secrets.VITE_FIREBASE_PHOTOS_API_KEY }}
          VITE_FIREBASE_PHOTOS_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_PHOTOS_AUTH_DOMAIN }}
          VITE_FIREBASE_PHOTOS_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PHOTOS_PROJECT_ID }}
          VITE_FIREBASE_PHOTOS_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_PHOTOS_STORAGE_BUCKET }}
          VITE_FIREBASE_PHOTOS_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_PHOTOS_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_PHOTOS_APP_ID: ${{ secrets.VITE_FIREBASE_PHOTOS_APP_ID }}
          VITE_FIREBASE_VIDEOS_API_KEY: ${{ secrets.VITE_FIREBASE_VIDEOS_API_KEY }}
          VITE_FIREBASE_VIDEOS_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_VIDEOS_AUTH_DOMAIN }}
          VITE_FIREBASE_VIDEOS_PROJECT_ID: ${{ secrets.VITE_FIREBASE_VIDEOS_PROJECT_ID }}
          VITE_FIREBASE_VIDEOS_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_VIDEOS_STORAGE_BUCKET }}
          VITE_FIREBASE_VIDEOS_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_VIDEOS_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_VIDEOS_APP_ID: ${{ secrets.VITE_FIREBASE_VIDEOS_APP_ID }}

      - name: Desplegar a Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PHOTOS }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID_PHOTOS }}
